
drop table R99FILES.rtrn;
drop table R99FILES.rtrncond;
drop table R99FILES.rtrndisp;
drop table R99FILES.rtrnitm;
drop table R99FILES.rtrnitmdtl;
drop table R99FILES.rtrnnix;
drop table R99FILES.rtrnnote;
drop table R99FILES.rtrnreas;
drop table R99FILES.rtrnstat;
create table R99FILES.rtrn (
     id bigint generated by default as identity,
     version bigint not null,
     addr1 varchar(30) not null,
     addr2 varchar(30) not null,
     addr3 varchar(30) not null,
     carrier_id for column carrierid varchar(255),
     carrcalled timestamp,
     changedate timestamp,
     changeuser varchar(30),
     city varchar(15) not null,
     confirm_date  for column confirmed timestamp,
     confirmed_by for column confirmby varchar(30),
     cntrycode varchar(3) not null,
     createdate timestamp not null,
     createuser varchar(30) not null,
     customer_id for column custid bigint not null,
     flddestry char(1) not null,    
     shipterms varchar(7) not null with default 'PREPAID',
     fgtclm char(1) not null,
     fgtclmrjct char(1) not null with default 'N',
     fgtclmamt numeric(9, 2),
     fgtclmchk varchar(50),
     fgtclmno varchar(50),
     fgtclmpaid timestamp,
     fgtclmsbm timestamp,
     fgtcstcr numeric(9, 2) not null,
     fgtincstdb numeric(9, 2) not null,
     frttrk varchar(25),
     mfgdb char(1) not null,
     name varchar(30) not null,
     nora char(1) not null,
     received_by for column receivedby varchar(30),
     stkcstdb numeric(9, 2) not null,
     rtrndate timestamp,
     hndcstcr numeric(9, 2) not null,
     state varchar(255) not null,
     status_id for column statusid varchar(255) not null,
     ship_via_id for column shipvia varchar(30),
     warehouse varchar(3) not null,
     zipcode varchar(9) not null,
     fghtdsc bigint,
     shphnddsc bigint,
     debit_memo_created for column dbcrtdat timestamp,
     invdisc numeric(5,3),
     fgtcrdistr varchar(3),
     primary key (id)) 
    rcdfmt rrtrn;
create table R99FILES.rtrncond (id bigint generated by default as identity,
     version bigint not null,
     code varchar(255) not null,
     primary key (id)) rcdfmt rrtrncond;
create table R99FILES.rtrndisp (id bigint generated by default as identity,
     version bigint not null,
     code varchar(255) not null,
     primary key (id)) rcdfmt rrtrndisp;
create table R99FILES.rtrnitm (id bigint generated by default as identity,
     version bigint not null,
     authQty integer not null,
     descr varchar(255) not null,
     ra_id for column raid bigint not null,
     itemno varchar(15) not null,
     nora char(1) not null,
     orderno integer not null,
     ship_no integer not null,
     reason_id for column reasonid bigint not null,
     rcvqty integer not null,
     unitprice numeric(9, 2) not null,
     primary key (id)) rcdfmt rrtrnitm;
create table R99FILES.rtrnitmdtl (id bigint generated by default as identity,
     version bigint not null,
     cond_id  for column condid bigint,
     disp_id for column dispid bigint,
     fgtclmnix bigint,
     fgtclmamt numeric(9, 2),
     fgtclmgl char(3),
     return_item_id for column rtrnitmid bigint not null,
     primary key (id)) rcdfmt rrtrnitmdt;
create table R99FILES.rtrnnix (id bigint generated by default as identity,
     version bigint not null,
     code varchar(255) not null,
     primary key (id)) rcdfmt rrtrnnix;
create table R99FILES.rtrnnote (id bigint generated by default as identity,
     version bigint not null,
     createdate timestamp not null,
     ra_id for column raid bigint not null,
     note varchar(255) not null,
     pdfshow char(1) not null,
     user varchar(255) not null,
     primary key (id)) rcdfmt rrtrnnote;
create table R99FILES.rtrnreas (id bigint generated by default as identity,
     version bigint not null,
     code varchar(255) not null,
     crs_reason_id for column crsreascod varchar(2) not null,
     primary key (id));
create table R99FILES.rtrnstat (code varchar(255) not null,
     collcklvl integer not null,
     descr varchar(255) not null,
     primary key (code)) rcdfmt rrtrnstat;
create table R99FILES.rtrnfgtdsc (
     id bigint generated by default as identity,
     version bigint not null,
     descr varchar(30) not null,
     primary key (id));
     
alter table R99FILES.rtrn add constraint FK3593FEA7CA2499 foreign key (fgtclmnix) references R99FILES.rtrnnix;
alter table R99FILES.rtrn add constraint FK3593FEB57EB997 foreign key (status_id) references R99FILES.rtrnstat;
alter table R99FILES.rtrn add constraint FK3593FEF2150B47 foreign key (customer_id) references R99FILES.custmast;
alter table R99FILES.rtrn add constraint FK3593FEC198DAC8 foreign key (shphnddsc) references R99FILES.rtrnfgtdsc;
alter table R99FILES.rtrn add constraint FK3593FEE060527E foreign key (fghtdsc) references R99FILES.rtrnfgtdsc;
alter table R99FILES.rtrnitm add constraint FK5AF29BE4AD43E2CA foreign key (ra_id) references R99FILES.rtrn;
alter table R99FILES.rtrnitm add constraint FK5AF29BE4674C057 foreign key (reason_id) references R99FILES.rtrnreas;
alter table R99FILES.rtrnitmdtl add constraint FKAEACAF78B632AE36 foreign key (cond_id) references R99FILES.rtrncond;
alter table R99FILES.rtrnitmdtl add constraint FKAEACAF78AF003128 foreign key (return_item_id) references R99FILES.rtrnitm;
alter table R99FILES.rtrnitmdtl add constraint FKAEACAF7866909D92 foreign key (disp_id) references R99FILES.rtrndisp;
alter table R99FILES.rtrnnote add constraint FK36314F0AD43E2CA foreign key (ra_id) references R99FILES.rtrn;
alter table R99FILES.rtrnreas add constraint FK364BEA3FD1520C8 foreign key (crs_reason_id) references o99files.oersnc;
--CRTJRNRCV JRNRCV(R99FILES/RTRNRCV) TEXT('for Return Authorization tables')
--CRTJRN JRN(R99FILES/RTRNJRN) JRNRCV(R99FILES/RTRNRCV)
--STRJRNPF FILE(R99FILES/RTRN R99FILES/RTRNITM R99FILES/RTRNITMDTL R99FILES/RTRNNOTE) JRN(R99FILES/RTRNJRN) IMAGES(*BOTH)

